### ISSUE TITLE
Failure on export/import

### ISSUE THREAD

**Issue by xavierfoucrier** [Metric/Atom-Auto-Uglify#9]
Hi @Metric, I got another bug with your package.

When using the code below, the package create a file `app.min.js` containing "undefined" and there is no error displayed by Atom. Seems that this comes from the ES6+ validation, but not sure: that's why I create a new issue.

in module/hello.js:
`export function hello() { return "Hello"; }`

in app.js, I got:
`import {hello} from './module/hello.js';`

**Comment by Metric** [comment]
Are you using 'use strict'; at the top of the file for the first line? You
should always use it if you are using ecma6+.

**Comment by xavierfoucrier** [comment]
Hi @Metric!

Yep, I am always using `'use strict';` Did this code works fine on your machine?

**Comment by Metric** [comment]
Yes, it is working fine on my machine.

**Comment by Metric** [comment]
@xavierfoucrier Please verify you do not have any syntax errors in your code. It appears uglify-es spits out undefined when there is a syntax error. Use JS-Lint or something to make sure there are no syntax errors.

**Comment by xavierfoucrier** [comment]
I will check asap.

**Comment by xavierfoucrier** [comment]
Sorry, my fault :/ ... seems to work now. I forgot a `use strict` inside the module file `hello.js`. Never mind, I close the issue and will be more attentive in the future :+1:
